### ISSUE TITLE
[Bug]: Small size of "bindings" column of the "slow_logs" table

### ISSUE THREAD

**Issue by gregoriohc** [halilcosdu/laravel-slower#10]
### What happened?

If you have a lot of bindings on your slow query, the `bindings` column 255 length it will not be enough and it will generates an error when trying to save the entry.

### How to reproduce the bug

Execute a slow query with a lot of (or long) bindings.

### Package Version

1.0.5

### PHP Version

8.2.0

### Laravel Version

11

### Which operating systems does with happen with?

Linux

### Notes

I have solved the problem changing the `bindings` column type in https://github.com/halilcosdu/laravel-slower/blob/main/database/migrations/create_slower_table.php.stub#L14

```php
$table->longtext('bindings');
```

**Comment by halilcosdu** [comment]
Thanks for reporting fixed.
