### ISSUE TITLE
[Bug]: Error Creating Log Due to Incorrect Parameter Type

### ISSUE THREAD

**Issue by J2TeamNNL** [halilcosdu/laravel-slower#22]
### What happened?

I am encountering an issue with the laravel-slower package where logs are not being saved. The error message received is as follows:
`Illuminate\Database\Grammar::parameterize(): Argument #1 ($values) must be of type array, string given, called in /var/www/sh_backend_api/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 1060
`

Additional Information:
The issue seems to be related to the `bindings` being passed as an array, which causes the error. If the `bindings` are passed as a string, the error does not occur. 
`vendor/halilcosdu/laravel-slower/src/SlowerServiceProvider.php:78`

Please provide any insights or fixes for this issue. Thank you.

### How to reproduce the bug

1. Attempt to save a log entry.
2. Observe the error message related to Illuminate\Database\Grammar::parameterize().

### Package Version

1.1

### PHP Version

8.1

### Laravel Version

10.9

### Which operating systems does with happen with?

macOS

**Comment by halilcosdu** [comment]
Checking ty.

**Comment by halilcosdu** [comment]
I was unable to reproduce the error. If you have a sample repository or could provide more details, I would be happy to review it. If this will take a longer time, I can send you a PR for review. @J2TeamNNL

**Comment by J2TeamNNL** [comment]
```php
SlowLog::query()->create([
    'bindings' => ['test']
]);
```
I failed while trying insert like this

**Comment by halilcosdu** [comment]
<img width="943" alt="Screenshot 2024-09-12 at 23 39 46" src="https://github.com/user-attachments/assets/49abe383-b5d0-4078-bb76-9414f3888b34">
